// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxjogvtsemafljebjehp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4am9ndnRzZW1hZmxqZWJqZWhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NDIyNzEsImV4cCI6MjA3MjMxODI3MX0.b-Bq1rmTtMdj4o8nnnHQRV30tjxqaT_tD8qf1-jgcTY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});