/**
 * API Tester Component
 * 
 * A built-in API testing panel similar to Postman for testing REST endpoints
 * generated by Express/Node.js/Go/Java applications.
 * 
 * Features:
 * - Multiple HTTP methods (GET, POST, PUT, DELETE, PATCH)
 * - Request headers management
 * - Request body editor with JSON syntax highlighting
 * - Response viewer with syntax highlighting
 * - Request history
 * - Environment variables
 * - Response time tracking
 * - Status code indicators
 * - Export/Import collections
 */

import React, { useState, useCallback, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Send,
  Plus,
  Trash2,
  Copy,
  Download,
  Upload,
  Clock,
  CheckCircle,
  XCircle,
  AlertCircle,
  Code,
  Eye,
  EyeOff,
  Settings,
  History,
  Save
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { ScrollArea } from '@/components/ui/scroll-area';
import { Badge } from '@/components/ui/badge';
import { Separator } from '@/components/ui/separator';
import { Label } from '@/components/ui/label';
import { Switch } from '@/components/ui/switch';
import { useToast } from '@/hooks/use-toast';

export interface ApiRequest {
  id: string;
  name: string;
  method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH' | 'HEAD' | 'OPTIONS';
  url: string;
  headers: Record<string, string>;
  body: string;
  timestamp: Date;
}

export interface ApiResponse {
  status: number;
  statusText: string;
  headers: Record<string, string>;
  body: string;
  responseTime: number;
  size: number;
}

export interface ApiTesterProps {
  baseUrl?: string;
  onRequest?: (request: ApiRequest) => Promise<ApiResponse>;
  className?: string;
  detectedEndpoints?: Array<{
    method: string;
    path: string;
    description?: string;
  }>;
}

const HTTP_METHODS = ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'HEAD', 'OPTIONS'] as const;

const DEFAULT_HEADERS = {
  'Content-Type': 'application/json',
  'Accept': 'application/json',
};

export const ApiTester: React.FC<ApiTesterProps> = ({
  baseUrl = 'http://localhost:3000',
  onRequest,
  className = '',
  detectedEndpoints = []
}) => {
  const [currentRequest, setCurrentRequest] = useState<ApiRequest>({
    id: '',
    name: 'New Request',
    method: 'GET',
    url: baseUrl,
    headers: DEFAULT_HEADERS,
    body: '',
    timestamp: new Date()
  });

  const [response, setResponse] = useState<ApiResponse | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [requestHistory, setRequestHistory] = useState<ApiRequest[]>([]);
  const [savedRequests, setSavedRequests] = useState<ApiRequest[]>([]);
  const [showHeaders, setShowHeaders] = useState(false);
  const [showRawResponse, setShowRawResponse] = useState(false);
  const [environment, setEnvironment] = useState<Record<string, string>>({
    baseUrl: baseUrl,
    apiKey: '',
    token: ''
  });

  const { toast } = useToast();
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Handle request execution
  const handleSendRequest = useCallback(async () => {
    if (!currentRequest.url.trim()) {
      toast({
        title: "Invalid URL",
        description: "Please enter a valid URL",
        variant: "destructive"
      });
      return;
    }

    setIsLoading(true);
    const startTime = Date.now();

    try {
      let finalResponse: ApiResponse;

      if (onRequest) {
        // Use custom request handler
        finalResponse = await onRequest(currentRequest);
      } else {
        // Default fetch implementation
        const requestOptions: RequestInit = {
          method: currentRequest.method,
          headers: currentRequest.headers,
        };

        if (['POST', 'PUT', 'PATCH'].includes(currentRequest.method) && currentRequest.body) {
          requestOptions.body = currentRequest.body;
        }

        const response = await fetch(currentRequest.url, requestOptions);
        const responseText = await response.text();
        const responseTime = Date.now() - startTime;

        finalResponse = {
          status: response.status,
          statusText: response.statusText,
          headers: Object.fromEntries(response.headers.entries()),
          body: responseText,
          responseTime,
          size: new Blob([responseText]).size
        };
      }

      setResponse(finalResponse);
      
      // Add to history
      const requestWithId = {
        ...currentRequest,
        id: `req_${Date.now()}`,
        timestamp: new Date()
      };
      setRequestHistory(prev => [requestWithId, ...prev.slice(0, 49)]); // Keep last 50

      toast({
        title: "Request completed",
        description: `${finalResponse.status} ${finalResponse.statusText} (${finalResponse.responseTime}ms)`,
        variant: finalResponse.status >= 200 && finalResponse.status < 300 ? "default" : "destructive"
      });

    } catch (error) {
      const errorResponse: ApiResponse = {
        status: 0,
        statusText: 'Network Error',
        headers: {},
        body: error instanceof Error ? error.message : 'Unknown error occurred',
        responseTime: Date.now() - startTime,
        size: 0
      };
      
      setResponse(errorResponse);
      
      toast({
        title: "Request failed",
        description: error instanceof Error ? error.message : "Network error occurred",
        variant: "destructive"
      });
    } finally {
      setIsLoading(false);
    }
  }, [currentRequest, onRequest, toast]);

  // Handle header changes
  const updateHeader = useCallback((key: string, value: string) => {
    setCurrentRequest(prev => ({
      ...prev,
      headers: { ...prev.headers, [key]: value }
    }));
  }, []);

  const removeHeader = useCallback((key: string) => {
    setCurrentRequest(prev => {
      const newHeaders = { ...prev.headers };
      delete newHeaders[key];
      return { ...prev, headers: newHeaders };
    });
  }, []);

  const addHeader = useCallback(() => {
    const key = prompt('Header name:');
    if (key) {
      updateHeader(key, '');
    }
  }, [updateHeader]);

  // Save current request
  const saveRequest = useCallback(() => {
    const name = prompt('Request name:', currentRequest.name);
    if (name) {
      const savedRequest = {
        ...currentRequest,
        id: `saved_${Date.now()}`,
        name,
        timestamp: new Date()
      };
      setSavedRequests(prev => [savedRequest, ...prev]);
      toast({
        title: "Request saved",
        description: `"${name}" has been saved to your collection`
      });
    }
  }, [currentRequest, toast]);

  // Load request from history or saved
  const loadRequest = useCallback((request: ApiRequest) => {
    setCurrentRequest(request);
    setResponse(null);
  }, []);

  // Export collection
  const exportCollection = useCallback(() => {
    const collection = {
      name: 'API Collection',
      timestamp: new Date().toISOString(),
      requests: savedRequests,
      environment
    };
    
    const blob = new Blob([JSON.stringify(collection, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'api-collection.json';
    a.click();
    URL.revokeObjectURL(url);
  }, [savedRequests, environment]);

  // Import collection
  const importCollection = useCallback((event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const collection = JSON.parse(e.target?.result as string);
        if (collection.requests) {
          setSavedRequests(collection.requests);
        }
        if (collection.environment) {
          setEnvironment(collection.environment);
        }
        toast({
          title: "Collection imported",
          description: `Imported ${collection.requests?.length || 0} requests`
        });
      } catch (error) {
        toast({
          title: "Import failed",
          description: "Invalid collection file format",
          variant: "destructive"
        });
      }
    };
    reader.readAsText(file);
  }, [toast]);

  // Format JSON
  const formatJson = useCallback((jsonString: string) => {
    try {
      return JSON.stringify(JSON.parse(jsonString), null, 2);
    } catch {
      return jsonString;
    }
  }, []);

  // Get status color
  const getStatusColor = (status: number) => {
    if (status >= 200 && status < 300) return 'text-green-500';
    if (status >= 300 && status < 400) return 'text-yellow-500';
    if (status >= 400 && status < 500) return 'text-orange-500';
    if (status >= 500) return 'text-red-500';
    return 'text-gray-500';
  };

  // Get status icon
  const getStatusIcon = (status: number) => {
    if (status >= 200 && status < 300) return <CheckCircle className="w-4 h-4 text-green-500" />;
    if (status >= 400) return <XCircle className="w-4 h-4 text-red-500" />;
    return <AlertCircle className="w-4 h-4 text-yellow-500" />;
  };

  return (
    <Card className={`bg-card ${className}`}>
      <CardHeader className="pb-4">
        <div className="flex items-center justify-between">
          <CardTitle className="flex items-center space-x-2">
            <Send className="w-5 h-5 text-primary" />
            <span>API Tester</span>
          </CardTitle>
          <div className="flex items-center space-x-2">
            <Button variant="outline" size="sm" onClick={saveRequest}>
              <Save className="w-4 h-4 mr-2" />
              Save
            </Button>
            <Button variant="outline" size="sm" onClick={exportCollection}>
              <Download className="w-4 h-4 mr-2" />
              Export
            </Button>
            <Button variant="outline" size="sm" onClick={() => fileInputRef.current?.click()}>
              <Upload className="w-4 h-4 mr-2" />
              Import
            </Button>
            <input
              ref={fileInputRef}
              type="file"
              accept=".json"
              onChange={importCollection}
              className="hidden"
            />
          </div>
        </div>
      </CardHeader>

      <CardContent className="space-y-6">
        {/* Request Builder */}
        <div className="space-y-4">
          {/* Method and URL */}
          <div className="flex space-x-2">
            <Select
              value={currentRequest.method}
              onValueChange={(method) => setCurrentRequest(prev => ({ ...prev, method: method as any }))}
            >
              <SelectTrigger className="w-32">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {HTTP_METHODS.map(method => (
                  <SelectItem key={method} value={method}>
                    <Badge variant={method === 'GET' ? 'secondary' : method === 'POST' ? 'default' : 'outline'}>
                      {method}
                    </Badge>
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            
            <Input
              value={currentRequest.url}
              onChange={(e) => setCurrentRequest(prev => ({ ...prev, url: e.target.value }))}
              placeholder="Enter request URL..."
              className="flex-1"
            />
            
            <Button onClick={handleSendRequest} disabled={isLoading} className="px-6">
              {isLoading ? (
                <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
              ) : (
                <Send className="w-4 h-4" />
              )}
              {isLoading ? 'Sending...' : 'Send'}
            </Button>
          </div>

          {/* Detected Endpoints */}
          {detectedEndpoints.length > 0 && (
            <div className="space-y-2">
              <Label className="text-sm font-medium">Detected Endpoints:</Label>
              <div className="flex flex-wrap gap-2">
                {detectedEndpoints.map((endpoint, index) => (
                  <Button
                    key={index}
                    variant="outline"
                    size="sm"
                    onClick={() => setCurrentRequest(prev => ({
                      ...prev,
                      method: endpoint.method.toUpperCase() as any,
                      url: `${baseUrl}${endpoint.path}`
                    }))}
                    className="text-xs"
                  >
                    <Badge variant="outline" className="mr-2 text-xs">
                      {endpoint.method.toUpperCase()}
                    </Badge>
                    {endpoint.path}
                  </Button>
                ))}
              </div>
            </div>
          )}

          {/* Request Configuration Tabs */}
          <Tabs defaultValue="headers" className="w-full">
            <TabsList className="grid w-full grid-cols-4">
              <TabsTrigger value="headers">Headers</TabsTrigger>
              <TabsTrigger value="body">Body</TabsTrigger>
              <TabsTrigger value="auth">Auth</TabsTrigger>
              <TabsTrigger value="env">Environment</TabsTrigger>
            </TabsList>

            <TabsContent value="headers" className="space-y-3">
              <div className="flex items-center justify-between">
                <Label>Request Headers</Label>
                <Button variant="outline" size="sm" onClick={addHeader}>
                  <Plus className="w-4 h-4 mr-2" />
                  Add Header
                </Button>
              </div>
              <div className="space-y-2">
                {Object.entries(currentRequest.headers).map(([key, value]) => (
                  <div key={key} className="flex space-x-2">
                    <Input
                      value={key}
                      onChange={(e) => {
                        const newKey = e.target.value;
                        const newHeaders = { ...currentRequest.headers };
                        delete newHeaders[key];
                        newHeaders[newKey] = value;
                        setCurrentRequest(prev => ({ ...prev, headers: newHeaders }));
                      }}
                      placeholder="Header name"
                      className="flex-1"
                    />
                    <Input
                      value={value}
                      onChange={(e) => updateHeader(key, e.target.value)}
                      placeholder="Header value"
                      className="flex-1"
                    />
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => removeHeader(key)}
                      className="px-3"
                    >
                      <Trash2 className="w-4 h-4" />
                    </Button>
                  </div>
                ))}
              </div>
            </TabsContent>

            <TabsContent value="body" className="space-y-3">
              <Label>Request Body</Label>
              <Textarea
                value={currentRequest.body}
                onChange={(e) => setCurrentRequest(prev => ({ ...prev, body: e.target.value }))}
                placeholder="Enter request body (JSON, XML, etc.)"
                className="min-h-[200px] font-mono text-sm"
              />
              <div className="flex space-x-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setCurrentRequest(prev => ({ ...prev, body: formatJson(prev.body) }))}
                >
                  <Code className="w-4 h-4 mr-2" />
                  Format JSON
                </Button>
              </div>
            </TabsContent>

            <TabsContent value="auth" className="space-y-3">
              <Label>Authentication</Label>
              <div className="space-y-3">
                <div className="flex space-x-2">
                  <Input
                    placeholder="API Key"
                    value={environment.apiKey}
                    onChange={(e) => setEnvironment(prev => ({ ...prev, apiKey: e.target.value }))}
                  />
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => updateHeader('X-API-Key', environment.apiKey)}
                  >
                    Add to Headers
                  </Button>
                </div>
                <div className="flex space-x-2">
                  <Input
                    placeholder="Bearer Token"
                    value={environment.token}
                    onChange={(e) => setEnvironment(prev => ({ ...prev, token: e.target.value }))}
                  />
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => updateHeader('Authorization', `Bearer ${environment.token}`)}
                  >
                    Add to Headers
                  </Button>
                </div>
              </div>
            </TabsContent>

            <TabsContent value="env" className="space-y-3">
              <Label>Environment Variables</Label>
              <div className="space-y-2">
                {Object.entries(environment).map(([key, value]) => (
                  <div key={key} className="flex space-x-2">
                    <Input value={key} readOnly className="flex-1 bg-muted" />
                    <Input
                      value={value}
                      onChange={(e) => setEnvironment(prev => ({ ...prev, [key]: e.target.value }))}
                      placeholder="Value"
                      className="flex-1"
                    />
                  </div>
                ))}
              </div>
            </TabsContent>
          </Tabs>
        </div>

        <Separator />

        {/* Response Section */}
        {response && (
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center space-x-3">
                <h3 className="text-lg font-semibold">Response</h3>
                {getStatusIcon(response.status)}
                <Badge className={getStatusColor(response.status)}>
                  {response.status} {response.statusText}
                </Badge>
                <Badge variant="outline" className="flex items-center space-x-1">
                  <Clock className="w-3 h-3" />
                  <span>{response.responseTime}ms</span>
                </Badge>
                <Badge variant="outline">
                  {(response.size / 1024).toFixed(2)} KB
                </Badge>
              </div>
              
              <div className="flex items-center space-x-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setShowRawResponse(!showRawResponse)}
                >
                  {showRawResponse ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                  {showRawResponse ? 'Pretty' : 'Raw'}
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => navigator.clipboard.writeText(response.body)}
                >
                  <Copy className="w-4 h-4 mr-2" />
                  Copy
                </Button>
              </div>
            </div>

            {/* Response Headers */}
            <div className="space-y-2">
              <div className="flex items-center space-x-2">
                <Label className="text-sm font-medium">Response Headers</Label>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => setShowHeaders(!showHeaders)}
                >
                  {showHeaders ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                </Button>
              </div>
              
              {showHeaders && (
                <div className="bg-muted rounded-lg p-3 space-y-1">
                  {Object.entries(response.headers).map(([key, value]) => (
                    <div key={key} className="flex text-sm">
                      <span className="font-medium text-muted-foreground w-1/3">{key}:</span>
                      <span className="flex-1 font-mono">{value}</span>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* Response Body */}
            <div className="space-y-2">
              <Label className="text-sm font-medium">Response Body</Label>
              <ScrollArea className="h-[300px] w-full rounded-lg border">
                <pre className="p-4 text-sm font-mono whitespace-pre-wrap">
                  {showRawResponse ? response.body : formatJson(response.body)}
                </pre>
              </ScrollArea>
            </div>
          </div>
        )}

        {/* History and Saved Requests */}
        <Tabs defaultValue="history" className="w-full">
          <TabsList className="grid w-full grid-cols-2">
            <TabsTrigger value="history">
              <History className="w-4 h-4 mr-2" />
              History ({requestHistory.length})
            </TabsTrigger>
            <TabsTrigger value="saved">
              <Save className="w-4 h-4 mr-2" />
              Saved ({savedRequests.length})
            </TabsTrigger>
          </TabsList>

          <TabsContent value="history">
            <ScrollArea className="h-[200px]">
              <div className="space-y-2">
                {requestHistory.map((request) => (
                  <div
                    key={request.id}
                    className="flex items-center justify-between p-3 border rounded-lg cursor-pointer hover:bg-muted/50"
                    onClick={() => loadRequest(request)}
                  >
                    <div className="flex items-center space-x-3">
                      <Badge variant="outline">{request.method}</Badge>
                      <span className="font-mono text-sm truncate">{request.url}</span>
                    </div>
                    <span className="text-xs text-muted-foreground">
                      {request.timestamp.toLocaleTimeString()}
                    </span>
                  </div>
                ))}
              </div>
            </ScrollArea>
          </TabsContent>

          <TabsContent value="saved">
            <ScrollArea className="h-[200px]">
              <div className="space-y-2">
                {savedRequests.map((request) => (
                  <div
                    key={request.id}
                    className="flex items-center justify-between p-3 border rounded-lg cursor-pointer hover:bg-muted/50"
                    onClick={() => loadRequest(request)}
                  >
                    <div className="flex items-center space-x-3">
                      <Badge variant="outline">{request.method}</Badge>
                      <span className="font-medium">{request.name}</span>
                      <span className="font-mono text-sm text-muted-foreground truncate">
                        {request.url}
                      </span>
                    </div>
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={(e) => {
                        e.stopPropagation();
                        setSavedRequests(prev => prev.filter(r => r.id !== request.id));
                      }}
                    >
                      <Trash2 className="w-4 h-4" />
                    </Button>
                  </div>
                ))}
              </div>
            </ScrollArea>
          </TabsContent>
        </Tabs>
      </CardContent>
    </Card>
  );
};